export const COMPANION_HTML = `<!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Minecraft Image Builder</title><style>body{font:18px system-ui;max-width:650px;margin:24px auto;padding:16px;background:#13251c;color:white}input,select,textarea,button{box-sizing:border-box;width:100%;padding:12px;margin:8px 0}button{background:#76dd9b}pre{white-space:pre-wrap;overflow-wrap:anywhere}</style><h1>Minecraft Image-to-Build</h1><p>اختر حتى ثلاث صور للمبنى. يتم إرسال الصور إلى مزود Vision؛ لا تُحفظ الصور في جلسة الخادم. رابط الجلسة خاص بك وينتهي خلال ساعة.</p><input id="images" type="file" accept="image/jpeg,image/png,image/webp" multiple><input id="views" placeholder="front, side, rear"><textarea id="prompt" placeholder="صف المبنى أو تعديل الخطة بالعربية / English"></textarea><select id="detail"><option>FAST</option><option selected>BALANCED</option><option>DETAILED</option><option>ULTRA</option></select><input id="scale" type="number" min="0.25" max="4" step="0.25" value="1"><button id="generate">Analyze images / تعديل الخطة</button><button id="download" disabled>Download BuildPlan JSON</button><pre id="result"></pre><script type="module">
const token=location.hash.slice(1)||sessionStorage.getItem('aibuilder:session')||'';if(/^[a-f0-9]{32}$/.test(token))sessionStorage.setItem('aibuilder:session',token);history.replaceState(null,'',location.pathname);let plan;
const byId=id=>document.getElementById(id);
async function normalize(file,view){
 if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>12000000)throw Error('Unsupported or oversized image');
 let bitmap;try{bitmap=await createImageBitmap(file,{imageOrientation:'from-image'});}catch{throw Error('Corrupt or unsupported image / الصورة تالفة أو غير مدعومة');}
 if(bitmap.width*bitmap.height>24000000){bitmap.close();throw Error('Image resolution exceeds 24MP');}
 const factor=Math.min(1,1536/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*factor));canvas.height=Math.max(1,Math.round(bitmap.height*factor));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();
 const data=canvas.toDataURL('image/jpeg',.8);if(data.length>1500000)throw Error('Compressed image still too large');return {data,width:canvas.width,height:canvas.height,view};
}
byId('generate').onclick=async()=>{const button=byId('generate');button.disabled=true;try{
 if(!/^[a-f0-9]{32}$/.test(token))throw Error('Open the private session link created in Minecraft');
 const prompt=byId('prompt').value.trim();if(prompt.length<3||prompt.length>1200)throw Error('Prompt must be 3-1200 characters');const scale=Number(byId('scale').value);if(!Number.isFinite(scale)||scale<.25||scale>4)throw Error('Scale must be 0.25-4');const files=[...byId('images').files];if(files.length>3)throw Error('Maximum 3 images');const views=byId('views').value.split(',');const images=[];for(let i=0;i<files.length;i++)images.push(await normalize(files[i],(views[i]||'view '+(i+1)).trim()));
 byId('result').textContent='Analyzing / جارٍ التحليل…';const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),60000);let response,data;try{response=await fetch('/image/session/'+token,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({prompt,images,detail:byId('detail').value,scale}),signal:controller.signal});data=await response.json();}finally{clearTimeout(timer);}if(!response.ok)throw Error(data.error||'Backend failed');plan=data.plan;byId('result').textContent=JSON.stringify({name:plan.blueprint.name,size:plan.dimensions,writes:plan.estimates.block_writes,assumptions:plan.assumptions,choices:plan.open_choices},null,2);byId('download').disabled=false;byId('images').value='';
 }catch(error){byId('result').textContent=error.name==='AbortError'?'Connection timed out / انتهت مهلة الاتصال؛ حاول مجددًا':error.message;}finally{button.disabled=false;}};
byId('download').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(plan)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='Minecraft-BuildPlan.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
</script></html>`;
