// TEST ONLY: deterministic API double, never packaged or used by production.
export type Vector3={x:number;y:number;z:number};
export class BlockPermutation{constructor(public type:{id:string},private states:Record<string,unknown>={}){} static resolve(id:string,states:Record<string,unknown>={}){if('invalid_state' in states)throw Error('Invalid permutation');return new BlockPermutation({id},states);}getAllStates(){return this.states;}}
export const BlockTypes={get:(id:string)=>id.startsWith('minecraft:')?{id}:undefined};
export class BlockVolume{constructor(public from:Vector3,public to:Vector3){}}
const properties=new Map<string,unknown>();const cells=new Map<string,BlockPermutation>();const structures=new Map<string,Map<string,BlockPermutation>>();let intervals:Array<()=>void>=[];
export const faults={fillAfter:undefined as number|undefined,propertyWrites:undefined as number|undefined};
export const system={currentTick:0,runInterval(fn:()=>void){intervals.push(fn);return intervals.length;}};
const key=(p:Vector3)=>[p.x,p.y,p.z].join(',');
export const dimension={id:'minecraft:overworld',heightRange:{min:-64,max:320},loaded:true,isChunkLoaded(_p:Vector3){return this.loaded;},getBlock(p:Vector3){if(!this.loaded)throw Error("Chunk unloaded");const permutation=cells.get(key(p))??BlockPermutation.resolve('minecraft:air');return {permutation,isAir:permutation.type.id==='minecraft:air'};},setBlockPermutation(p:Vector3,v:BlockPermutation){cells.set(key(p),v);},fillBlocks(volume:BlockVolume,p:BlockPermutation){let written=0;for(let x=volume.from.x;x<=volume.to.x;x++)for(let y=volume.from.y;y<=volume.to.y;y++)for(let z=volume.from.z;z<=volume.to.z;z++) {cells.set(key({x,y,z}),p);written++;if(faults.fillAfter!==undefined && written>=faults.fillAfter){faults.fillAfter=undefined;throw Error("Injected partial fill failure");}}}};
export const player={id:'player1',dimension,messages:[] as string[],sendMessage(m:string){this.messages.push(m);},onScreenDisplay:{setActionBar(_s:string){}}};
export const world={getAllPlayers:()=>[player],getDimension:(_id:string)=>dimension,getDynamicProperty:(k:string)=>properties.get(k),setDynamicProperty:(k:string,v:unknown)=>{if(faults.propertyWrites!==undefined && k.includes('active_job_progress')){if(faults.propertyWrites<=0)throw Error('Injected checkpoint storage failure');faults.propertyWrites--;}if(typeof v==='string' && new TextEncoder().encode(v).byteLength>32767)throw Error('Dynamic property exceeds 32KB UTF-8');return v===undefined?properties.delete(k):properties.set(k,v);},structureManager:{createFromWorld(id:string,_dim:unknown,from:Vector3,to:Vector3){const map=new Map<string,BlockPermutation>();for(let x=from.x;x<=to.x;x++)for(let y=from.y;y<=to.y;y++)for(let z=from.z;z<=to.z;z++)map.set(key({x,y,z}),dimension.getBlock({x,y,z}).permutation);structures.set(id,map);},get:(id:string)=>structures.get(id),delete:(id:string)=>structures.delete(id),place(id:string){for(const [k,v]of structures.get(id)!)cells.set(k,v);}}};
export const StructureSaveMode={World:1};
export function ticks(n:number){for(let i=0;i<n;i++){system.currentTick++;for(const fn of intervals)fn();}}
export function stopIntervals(){intervals=[];}
export function reset(){properties.clear();cells.clear();structures.clear();intervals=[];dimension.loaded=true;player.messages=[];faults.fillAfter=undefined;faults.propertyWrites=undefined;}
